[package]
name = "auth_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
tracing-subscriber = "0.3.18"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
ratatui = "0.26.1"
crossterm = "0.27.0"
clap = { version = "4.5.4", features = ["derive"] }
[dependencies.uuid]
version = "1.8.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",             # Enable serialization/deserialization of UUIDs
]
