services:
  app:
    depends_on:
      mysql:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '1'
        reservations:
          memory: 64M
          cpus: '0.5'
    environment:
      DATABASE_URL: mysql://root:toor@mysql:3306/nebula_dev
#      DATABASE_URL: sqlite://nebula_dev.db
      PASSWORD_HASHING_SCHEME: 'bcrypt_low'
      SECRET: "secret"
      RABBITMQ_URL: amqp://rabbit:5672
      VERIFICATION_REQUIRED: false
      EVENT_DRIVEN: true
      AUTH_STRATEGY: stateful
      LOG_LEVEL: info
      CLEANUP_INTERVAL_IN_MINUTES: 1
      RABBITMQ_EXCHANGE_NAME: nebula.auth.dev
    ports:
      - "8080:8080"

  mysql:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbit:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
