services:
  app:
    depends_on:
      mysql:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    environment:
      DATABASE_URL: mysql://root:toor@mysql:3306/auth_service_dev
      PASSWORD_HASHING_SCHEME: 'argon2'
      SECRET: "secret"
      RABBITMQ_URL: amqp://rabbit:5672
      VERIFICATION_REQUIRED: true
      EVENT_DRIVEN: true
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbit:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
