services:
  app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    environment:
      DATABASE_URL: mysql://root:toor@mysql:3306/auth_service_dev
      PASSWORD_HASHING_SCHEME: 'bcrypt_low'
      SECRET: "secret"
      RABBITMQ_URL: amqp://rabbit:5672
      VERIFICATION_REQUIRED: true
      EVENT_DRIVEN: true
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: auth_service_dev
    ports:
      - "3306:3306"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
