services:
  app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    environment:
      DATABASE_URL: mysql://root:toor@mysql:3306/auth_service_dev
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: auth_service_dev
    ports:
      - "3306:3306"
