services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: user_auth
    ports:
      - "3306:3306"
