name: Rust auth api deployment

on:
  workflow_dispatch: ~
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Dockerfile"
      - "tests/**"
      - "migrations/**"
      - ".github/workflows/cd-v2.yml"
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rocketarminek/auth-api-rust

jobs:
  prepare-vendor:
    runs-on: ubuntu-latest
    name: "Prepare vendor"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.2
          profile: minimal
          override: true
      - name: Download vendors
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: vendor
          path: vendor
          run-id: 8941868538
      - name: Ls vendors
        run: ls -al vendor
      - name: Cargo update vendors
        run: cargo vendor
      - name: Upload vendors
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor

#  prepare-vendor:
#    runs-on: ubuntu-20.04
#    name: "Prepare vendor"
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Log in to the Container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: false
#          target: testing
#          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-testing
#          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-testing,mode=max
#      - name: Test host files
#        run: |
#          ls -al
#          ls -al /app/target
