name: CI

on:
  workflow_dispatch: ~
  release:
    types: [published]
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Dockerfile"
      - "tests/**"
      - "migrations/**"
      - ".github/workflows/ci.yml"
    branches:
      - "main"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rocketarminek/auth-api-rust

jobs:
  dist-cache:
    runs-on: ubuntu-22.04
    name: "Prepare production docker image"
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        if: github.event_name == 'release'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ github.event_name == 'release' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          driver-opts: |
            image=moby/buildkit:master
            network=host
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |-
            type=raw,value=test-latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ github.event_name == 'release' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          target: server
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
            ${{ github.event_name == 'release' && format('type=registry,ref={0}:buildcache-arm64', env.REGISTRY, env.IMAGE_NAME) || '' }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-amd64
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ github.job }}-${{ matrix.platform }},mode=max
          outputs: type=registry
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  prepare:
    runs-on: ubuntu-22.04
    name: "Download vendors & Build tests"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Restore cached dependencies
        id: restore-build
        uses: actions/cache/restore@v4
        with:
          path: |
            vendor
            target/debug/deps
            target/debug/build
            target/debug/.fingerprint
            target/debug/.cargo-lock
            target/debug/incremental
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'src/**', 'tests/**') }}

      - name: Setup vendored dependencies
        if: steps.restore-build.outputs.cache-hit != 'true'
        run: |
          echo "CACHE HIT"
          echo ${{steps.restore-build.outputs.cache-hit}}
          cargo vendor

      - name: Build tests
        if: steps.restore-build.outputs.cache-hit != 'true'
        run: cargo test --no-run

      - name: Save cache
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            vendor
            target/debug/deps
            target/debug/build
            target/debug/.fingerprint
            target/debug/.cargo-lock
            target/debug/incremental
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'src/**', 'tests/**') }}

  acceptance-test:
    needs:
      - prepare
    runs-on: ubuntu-22.04
    name: "Acceptance"
    timeout-minutes: 5
    strategy:
      matrix:
        db:
          - engine: "sqlite"
            url: "sqlite://test.db"
          - engine: "mysql"
            url: "mysql://root:toor@127.0.0.1:3306/auth_service_test"
            service: "mysql:8.4"
          - engine: "mysql"
            url: "mysql://root:toor@127.0.0.1:3306/auth_service_test"
            service: "mysql:9.4"
        rabbitmq:
          - version: "4"
    services:
      mysql:
        image: ${{ (matrix.db.service) && matrix.db.service || '' }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: toor
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptoor"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=40s
      rabbit:
        image: rabbitmq:${{matrix.rabbitmq.version}}-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd="rabbitmq-diagnostics check_port_connectivity"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5
          --health-start-period=90s
    env:
      DATABASE_ENGINE: ${{ matrix.db.engine }}
      DATABASE_URL: ${{ matrix.db.url }}
      RABBITMQ_URL: amqp://127.0.0.1:5672
      RABBITMQ_EXCHANGE_AUTO_DELETE: true
      RABBITMQ_EXCHANGE_DURABLE: false
      RABBITMQ_EXCHANGE_NAME: auth.test
      SECRET: secret
      PASSWORD_HASHING_SCHEME: bcrypt_low
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            vendor
            target/debug/deps
            target/debug/build
            target/debug/.fingerprint
            target/debug/.cargo-lock
            target/debug/incremental
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'src/**', 'tests/**') }}
      - name: Run tests
        run: cargo test

  performance-test:
    continue-on-error: true
    runs-on: ubuntu-22.04
    needs: dist-cache
    name: "Performance"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        db:
          - engine: "sqlite"
            url: "sqlite://test.db"
          - engine: "mysql"
            url: "mysql://root:toor@mysql:3306/auth_service_test"
            service: "mysql:9.4"
        rabbitmq:
          - version: "4"
    services:
      mysql:
        image: ${{ (matrix.db.service) && matrix.db.service || '' }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: toor
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptoor"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=40s
      rabbit:
        image: rabbitmq:${{matrix.rabbitmq.version}}-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd="rabbitmq-diagnostics check_port_connectivity"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5
          --health-start-period=90s
      app:
        image: ghcr.io/rocketarminek/auth-api-rust:test-latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:8080
        env:
          DATABASE_ENGINE: ${{ matrix.db.engine }}
          DATABASE_URL: ${{ matrix.db.url }}
          PASSWORD_HASHING_SCHEME: bcrypt_low
          SECRET: secret
          RABBITMQ_URL: amqp://rabbit:5672
          VERIFICATION_REQUIRED: false
          MESSAGE_PUBLISHER_ENGINE: rabbitmq
        options: >-
          --health-cmd="app health-check"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - name: Run k6 auth flow test scenario
        run: k6 run tests/performance/scenarios/auth_flow.js --throw --quiet

  zap-scan:
    runs-on: ubuntu-22.04
    name: "Security"
    needs: dist-cache
    timeout-minutes: 10
    strategy:
      matrix:
        db:
          - engine: "sqlite"
            url: "sqlite://test.db"
          - engine: "mysql"
            url: "mysql://root:toor@mysql:3306/auth_service_test"
            service: "mysql:9.4"
        rabbitmq:
          - version: "4"
    services:
      mysql:
        image: ${{ (matrix.db.service) && matrix.db.service || '' }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: toor
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptoor"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=40s
      rabbit:
        image: rabbitmq:4-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd="rabbitmq-diagnostics check_port_connectivity"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5
          --health-start-period=90s
      app:
        image: ghcr.io/rocketarminek/auth-api-rust:test-latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:8080
        env:
          DATABASE_ENGINE: ${{ matrix.db.engine }}
          DATABASE_URL: ${{ matrix.db.url }}
          PASSWORD_HASHING_SCHEME: bcrypt_low
          SECRET: secret
          RABBITMQ_URL: amqp://rabbit:5672
          VERIFICATION_REQUIRED: false
          MESSAGE_PUBLISHER_ENGINE: rabbitmq
        options: >-
          --health-cmd="app health-check"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s
    steps:
      - uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: false
          artifact_name: zap-scan-${{ matrix.db.engine }}-${{ github.run_id }}

  publish-server-image:
    runs-on: ubuntu-22.04
    name: "Publish server production image"
    timeout-minutes: 120
    needs:
      - acceptance-test
      - zap-scan
      - performance-test
      - dist-cache
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        if: github.event_name == 'release'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ github.event_name == 'release' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          driver-opts: |
            image=moby/buildkit:master
            network=host
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |-
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            type=raw,value=latest
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: server
          platforms: ${{ github.event_name == 'release' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
            ${{ github.event_name == 'release' && format('type=registry,ref={0}:buildcache-arm64', env.REGISTRY, env.IMAGE_NAME) || '' }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-amd64
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ github.job }}-${{ matrix.platform }},mode=max
          outputs: type=registry
          build-args: |
            BUILDKIT_INLINE_CACHE=1
