name: CI

on:
  workflow_dispatch: ~
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Dockerfile"
      - "tests/**"
      - "migrations/**"
      - ".github/workflows/ci.yml"
    branches:
      - "main"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rocketarminek/auth-api-rust

jobs:
  dist-cache:
    runs-on: ubuntu-22.04
    name: "Prepare production docker image"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |-
            type=raw,value=test-latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          target: server
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max

  prepare:
    runs-on: ubuntu-22.04
    name: "Download vendors & Build tests"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Restore cached dependencies
        id: restore-build
        uses: actions/cache/restore@v4
        with:
          path: |
            vendor
            target/debug/deps
            target/debug/build
            target/debug/.fingerprint
            target/debug/.cargo-lock
            target/debug/incremental
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'src/**', 'tests/**') }}

      - name: Setup vendored dependencies
        if: steps.restore-build.outputs.cache-hit != 'true'
        run: |
          echo "CACHE HIT"
          echo ${{steps.restore-build.outputs.cache-hit}}
          cargo vendor

      - name: Build tests
        if: steps.restore-build.outputs.cache-hit != 'true'
        run: cargo test --no-run

      - name: Save cache
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            vendor
            target/debug/deps
            target/debug/build
            target/debug/.fingerprint
            target/debug/.cargo-lock
            target/debug/incremental
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'src/**', 'tests/**') }}

  performance-and-security-test:
    runs-on: ubuntu-22.04
    needs: dist-cache
    name: "Performance & Security"
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        strategy:
          - "stateful"
          - "stateless"
        db:
#          - engine: "sqlite"
#            url: "sqlite://test.db"
          - engine: "mysql"
            url: "mysql://root:toor@mysql:3306/auth_service_test"
            service: "mysql:8.4"
        rabbitmq:
          - version: "4"
    services:
      mysql:
        image: ${{ (matrix.db.service) && matrix.db.service || '' }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: toor
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptoor"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=40s
      rabbit:
        image: rabbitmq:${{matrix.rabbitmq.version}}-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd="rabbitmq-diagnostics check_port_connectivity"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5
          --health-start-period=90s
      app:
        image: ghcr.io/rocketarminek/auth-api-rust:test-latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:8080
        env:
          DATABASE_ENGINE: ${{ matrix.db.engine }}
          DATABASE_URL: ${{ matrix.db.url }}
          AUTH_STRATEGY: ${{ matrix.strategy }}
          PASSWORD_HASHING_SCHEME: bcrypt_low
          SECRET: secret
          RABBITMQ_URL: amqp://rabbit:5672
          VERIFICATION_REQUIRED: false
          EVENT_DRIVEN: true
        options: >-
          --health-cmd="app health-check"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - name: Run k6 auth flow test scenario
        run: k6 run tests/performance/scenarios/auth_flow.js --throw --quiet
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: false
          artifact_name: zap-scan-${{ matrix.db.engine }}-${{ matrix.strategy }}-${{ github.run_id }}

  acceptance-test:
    needs:
      - prepare
    runs-on: ubuntu-22.04
    name: "Acceptance"
    timeout-minutes: 5
    strategy:
      matrix:
        db:
          - engine: "sqlite"
            url: "sqlite://test.db"
          - engine: "mysql"
            url: "mysql://root:toor@127.0.0.1:3306/auth_service_test"
            service: "mysql:8.4"
        strategy:
          - "stateful"
          - "stateless"
        rabbitmq:
          - version: "4"
    services:
      mysql:
        image: ${{ (matrix.db.service) && matrix.db.service || '' }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: toor
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptoor"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=40s
      rabbit:
        image: rabbitmq:${{matrix.rabbitmq.version}}-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd="rabbitmq-diagnostics check_port_connectivity"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5
          --health-start-period=90s
    env:
      DATABASE_ENGINE: ${{ matrix.db.engine }}
      DATABASE_URL: ${{ matrix.db.url }}
      AUTH_STRATEGY: ${{ matrix.strategy }}
      RABBITMQ_URL: amqp://127.0.0.1:5672
      RABBITMQ_EXCHANGE_AUTO_DELETE: true
      RABBITMQ_EXCHANGE_DURABLE: false
      RABBITMQ_EXCHANGE_NAME: nebula.auth.test
      SECRET: secret
      PASSWORD_HASHING_SCHEME: bcrypt_low
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            vendor
            target/debug/deps
            target/debug/build
            target/debug/.fingerprint
            target/debug/.cargo-lock
            target/debug/incremental
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'src/**', 'tests/**') }}
      - name: Run tests
        run: cargo test

  publish-server-image:
    runs-on: ubuntu-22.04
    name: "Publish server production image"
    needs:
      - acceptance-test
      - performance-and-security-test
      - dist-cache
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |-
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: server
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache

  test-examples:
    runs-on: ubuntu-latest
    needs: publish-server-image
    defaults:
      run:
        working-directory: examples/basic
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: examples/basic
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Start services
        run: docker compose up -d --build
      - name: Wait for services to be ready
        run: |
          # Wait for MySQL
          timeout 60s bash -c 'until docker compose exec -T mysql mysqladmin ping -h localhost -u root -ptoor; do sleep 1; done'
          
          # Wait for RabbitMQ
          timeout 60s bash -c 'until docker compose exec -T rabbit rabbitmq-diagnostics check_port_connectivity; do sleep 1; done'
          
          # Additional wait to ensure all services are fully initialized
          sleep 10
      - name: Run e2e tests
        run: |
          cargo vendor
          cargo test --test e2e -- --nocapture
      - name: Show logs on failure
        if: failure()
        run: docker compose logs
      - name: Cleanup
        if: always()
        run: docker compose down -v
