name: Examples E2E Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/basic

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: app

      - name: Start services
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          # Wait for MySQL
          timeout 60s bash -c 'until docker compose exec -T mysql mysqladmin ping -h localhost -u root -ptoor; do sleep 1; done'
          
          # Wait for RabbitMQ
          timeout 60s bash -c 'until docker compose exec -T rabbit rabbitmq-diagnostics check_port_connectivity; do sleep 1; done'
          
          # Additional wait to ensure all services are fully initialized
          sleep 10

      - name: Run e2e tests
        run: |
          cd app
          cargo test --test e2e -- --nocapture

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Cleanup
        if: always()
        run: docker compose down -v
